void separateDuplicateEventNumberEntries(){

  // Example of Root macro to copy a subset of a Tree to a new Tree
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1

  gROOT->Reset();
  gSystem->Load("libAnitaEvent.so");

  //Get old file, old tree and set top branch address
  Int_t run = 283;
  TString baseDir = "~/UCL/ANITA/";
  
  // TString oldFileName = baseDir + TString::Format("flight1415/root/run%d/headFile%d.root", run, run);
  TString oldFileName = baseDir + TString::Format("flight1415/root/run%d/calEventFile%d.root", run, run);  
  TFile *oldfile = new TFile(oldFileName);
  // TTree *oldtree = (TTree*)oldfile->Get("headTree");
  TTree *oldtree = (TTree*)oldfile->Get("eventTree");  
  Int_t nentries = (Int_t)oldtree->GetEntries();

  // RawAnitaHeader* header = NULL;
  // oldtree->SetBranchAddress("header",&header);
  CalibratedAnitaEvent* calEvent = NULL;
  oldtree->SetBranchAddress("event",&calEvent);  

  //Create a new file + a clone of old tree in new file
  // TString newFileName = baseDir + TString::Format("flight1415/root/run%d/trimmedHeadFile%d.root",
  TString newFileName = baseDir + TString::Format("flight1415/root/run%d/trimmedCalEventFile%d.root",	  
						  run, run);  
  TFile *newfile = new TFile(newFileName,"recreate");
  TTree *newtree = oldtree->CloneTree(0);

  // TString newFileName2 = baseDir + TString::Format("flight1415/root/run%d/headFile%d.removedEvents.root",
  TString newFileName2 = baseDir + TString::Format("flight1415/root/run%d/calEventFile%d.removedEvents.root",
						   run, run);
  TFile *newfile2 = new TFile(newFileName2,"recreate");
  TTree *newtree2 = oldtree->CloneTree(0);
  
  const UInt_t firstDuplicatedEventNumber = 41518201;
  
  for (Int_t i=0;i<nentries; i++) {
    oldtree->GetEntry(i);
    // if (header->eventNumber < firstDuplicatedEventNumber){
    if (calEvent->eventNumber < firstDuplicatedEventNumber){      
      newtree->Fill();
    }
    else{
      newtree2->Fill();
    }
  }
  newtree->Print();
  newtree->AutoSave();
  newtree2->Print();
  newtree2->AutoSave();  
  delete oldfile;
  delete newfile;
  delete newfile2;  
}
